name: getenergy-website

on:
  push:
    branches:
      - 'dev'
      - 'main'

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: npm install
        run: npm install --legacy-peer-deps

      - name: Build application
        run: npm run build
        
      - name: Deploy to production 
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET }}
          SCRIPT_AFTER: |
            pm2 restart landing_page

